### ISSUE TITLE
Default language to show in URL?

### ISSUE THREAD

**Issue by smillerk2** [boudinov/mvc-5-routing-localization#2]
Is it possible to have a configuration switch or something that would force the generated URLs to include the default language? The example works fine with both "de" and "en" (default) but it would be great if "en" could always be written in rendered links.

**Comment by boudinov** [comment]
I added a web config setting PrefixDefaultCulture which you have to set to true

**Comment by smillerk2** [comment]
Works perfectly. Thank you.
